#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";

function printUsage() {
  process.stdout.write(
    [
      "fmweb-plugin init [plugin-name] [--dir <target-directory>]",
      "",
      "Examples:",
      "  fmweb-plugin init my-plugin",
      "  fmweb-plugin init crm-insights --dir ./plugins/crm-insights",
      ""
    ].join("\n")
  );
}

function toPluginId(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "fmweb-plugin";
}

function toPluginClassName(value) {
  const token = value
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((entry) => entry.charAt(0).toUpperCase() + entry.slice(1).toLowerCase())
    .join("");
  return token || "FMWebPlugin";
}

async function ensureDirectoryEmpty(dir) {
  try {
    const entries = await fs.readdir(dir);
    if (entries.length > 0) {
      throw new Error(`Target directory "${dir}" is not empty`);
    }
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      await fs.mkdir(dir, { recursive: true });
      return;
    }
    throw error;
  }
}

async function writePluginTemplate(targetDir, name) {
  const id = toPluginId(name);
  const className = toPluginClassName(name);
  const manifest = {
    id: `plugin.${id}`,
    name: name.trim() || "FM Web IDE Plugin",
    version: "0.1.0",
    compatibility: "^1.0.0",
    description: "Generated plugin scaffold for FM Web IDE",
    entry: "./src/index.ts"
  };

  const srcDir = path.join(targetDir, "src");
  await fs.mkdir(srcDir, { recursive: true });
  await fs.writeFile(
    path.join(targetDir, "manifest.json"),
    JSON.stringify(manifest, null, 2),
    "utf8"
  );
  await fs.writeFile(
    path.join(targetDir, "README.md"),
    `# ${manifest.name}

Generated by \`fmweb-plugin init\`.

## Local Dev

1. Implement \`src/index.ts\`
2. Register the plugin in your FM Web IDE runtime bootstrap
3. Run FM Web IDE and verify plugin activation logs
`,
    "utf8"
  );
  await fs.writeFile(
    path.join(srcDir, "index.ts"),
    `import type { FMPlugin } from "../../src/plugins";

export const ${className}: FMPlugin = {
  id: "${manifest.id}",
  version: "${manifest.version}",
  compatibility: "${manifest.compatibility}",
  activate(context) {
    context.logger.log("info", "Plugin activated");
  },
  deactivate() {
    // Optional teardown.
  }
};

export default ${className};
`,
    "utf8"
  );
}

async function run() {
  const args = process.argv.slice(2);
  const command = args[0];
  if (!command || command === "--help" || command === "-h") {
    printUsage();
    return;
  }
  if (command !== "init") {
    throw new Error(`Unknown command "${command}"`);
  }

  const nameArg = args[1] && !args[1].startsWith("--") ? args[1] : "fmweb-plugin";
  const dirFlagIndex = args.findIndex((entry) => entry === "--dir");
  const dirArg = dirFlagIndex >= 0 ? args[dirFlagIndex + 1] : undefined;
  const targetDir = path.resolve(process.cwd(), dirArg || `./${toPluginId(nameArg)}`);

  await ensureDirectoryEmpty(targetDir);
  await writePluginTemplate(targetDir, nameArg);
  process.stdout.write(`Created plugin scaffold at ${targetDir}\n`);
}

run().catch((error) => {
  const message = error instanceof Error ? error.message : String(error ?? "Unknown error");
  process.stderr.write(`fmweb-plugin failed: ${message}\n`);
  process.exitCode = 1;
});
